### ISSUE TITLE
First pix on 2 uni is blinking

### ISSUE THREAD

**Issue by kaeltaz** [mtongnz/ESP8266_ArtNetNode_v2#17]
First pix on 2 uni is blinking

https://www.youtube.com/watch?v=qbqkvZ2hWWU

**Comment by mtongnz** [comment]
I believe this is related to this issue: #15 

I am waiting on some new pixels to arrive (bought thanks to a couple of donations I've received) before I can fully test my fix.  At present I only have 150 pixels to test with :(

**Comment by mtongnz** [comment]
I've released beta4a.  It has a slightly slower data rate which will hopefully fix this issue.  Please try and let me know

**Comment by Alfiszcze** [comment]
I belive that it is universe problem because the same issue is with 1st pix on 3rd universe .
512 dmx /3 = 170 and leftover 2 slots from dmx universe.

**Comment by mtongnz** [comment]
Please try beta5 and see if it's better

**Comment by mtongnz** [comment]
OK.... I've actually found the cause of this.  It was nothing to do with timing - I was accidentally writing over the first 2 channels of uni 2 with channels 511 & 512 of the first uni.

beta5a should definitely fix this issue.  I've only got 150 pixels so please test and let me know.
