### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by nanu-c** [mtongnz/ESP8266_ArtNetNode_v2#20]
Would you mind to put also the source code in here, because i want to sligtly moidfy it to control a slide projector?
Everything is well done here. If not i will stick on the old version...

**Comment by mtongnz** [comment]
The source code will be coming eventually but I want to get all the features implemented first and a bit of testing done.  I've just got sACN and DMX input to add :)

**Comment by nanu-c** [comment]
Okey, I am not impatient ;)
