### ISSUE TITLE
Hotspot SSID

### ISSUE THREAD

**Issue by kaeltaz** [mtongnz/ESP8266_ArtNetNode_v2#26]
Hotspot SSID do not contain last digits of the MAC address

**Comment by mtongnz** [comment]
???

**Comment by kaeltaz** [comment]
This is not last digits of the MAC address

![zrzut ekranu 172](https://cloud.githubusercontent.com/assets/25663430/23107329/9b8d6ea6-f6fb-11e6-8b2c-d6f2272ee633.png)

**Comment by mtongnz** [comment]
It's not meant to be.  It's a 5 digit number derived from the chipID (which the ESP8266 does use to generate it's MAC address).

The purpose of the number is to ensure that if there are multiple units, they will have a unique SSID.  It will stay the same for the entire life of the unit as the chipID never changes.

This method is only used when the default hotspot SSID is in use.  If you change it, the number wont be used.

**Comment by mtongnz** [comment]
This is the code used to generate the SSID:

`// If it's the default WiFi SSID, make it unique
  if (strcmp(hotspotSSID, "espArtNetNode") == 0 || hotspotSSID[0] == '\0')
    sprintf(hotspotSSID, "espArtNetNode_%05u", (ESP.getChipId() & 0xFF));`
