### ISSUE TITLE
Wemos D1 mini

### ISSUE THREAD

**Issue by asm7100** [mtongnz/ESP8266_ArtNetNode_v2#30]
D4 (GPIO2) Has a 10K pullUp and a led on it, Not good, dosent work.
All led, full white on them.
Trying to use it with WS2812.

**Comment by mtongnz** [comment]
This is a hardware limitation, not software. Unfortunately they've designed their hardware poorly. Changing this in software will break other features of my firmware. Maybe just remove the LED and resistor.
I've reopened the other issue so discuss there
