### ISSUE TITLE
Tested on Wemos D1 Mini

### ISSUE THREAD

**Issue by asm7100** [mtongnz/ESP8266_ArtNetNode_v2#34]
Hi now i have testet the last to days.
It dos NOT at all on Wemos D1 mini. :-(

it will say it starts up, and my QLC+ can see it, but it will not controll the WS2812 thay only light white, all the time.

Can you try to make a version where you use gpio4 for port A? Just to test it.

Bye the way, QLC+ software can see your hardware (When Wemos D1mini runs with out anything connecet to it, so i expect that QLC+ can use your software to :-)

**Comment by asm7100** [comment]
Now i got it to work, jave gave it a shorter Short Name:
and a shorter Longer name?????

**Comment by asm7100** [comment]
WS2812 no port A (TX)

**Comment by mtongnz** [comment]
Could you please let me know what name you were using for long and short?

My code should limit the lengths to 20 & 60 respectively as defined by the Artnet v4 standard.

Also please check the new beta5b as it has slightly different compiler options used.

**Comment by asm7100** [comment]
eANNW 3-100
eANNW 3-100 - Matrix x 2

This is the two names i am using
And the new v2.0.0 (beta 5b) works fine.

**Comment by mtongnz** [comment]
Does the new beta work with the longer names you tried?
