### ISSUE TITLE
DMX IN

### ISSUE THREAD

**Issue by Lazerjules** [mtongnz/ESP8266_ArtNetNode_v2#48]
Hi Mtongnz

Fantastic project, excellent work!

Have you implemented DMX IN yet? I don't seem to be able to get it to work. 
DMX out on A and B no problem, working perfectly. 

Using DMX IN, I am assuming I should see the input values in DMX Workshop? Checking the node list I see what's in the attached picture so something is happening. 

Any advice would be much appreciated thank you. 

![dmx in](https://cloud.githubusercontent.com/assets/26973898/24854865/c4ac5740-1dd7-11e7-9add-97f716094c1a.JPG)

![Uploading image.png…]()

**Comment by mtongnz** [comment]
Ensure you set the DMX In broadcast address in the Web UI.  It should be working.  I'll check it again when I get a chance.

**Comment by Lazerjules** [comment]
Hi Matt
Perfect thanks. Operator error! I hadn't set the broadcast address! Apologies.
