### ISSUE TITLE
Sorry for the impatience, but...

### ISSUE THREAD

**Issue by TheSeven** [mtongnz/ESP8266_ArtNetNode_v2#52]
...it's May, and where is the source? ;)

**Comment by mtongnz** [comment]
Sorry - been working 17 hour days for the last week.  Finally got a half day off so it's now up :)

**Comment by TheSeven** [comment]
Wow, thanks a LOT! :)
While having a quick look I stumbled upon the ESTA and OEM codes in that source, which seem to be just randomly chosen.
I'd suggest using "OEM Unknown" (0x00ff) for the OEM code and the prototyping ESTA code (0x7fff) until you have obtained official ones.
