### ISSUE TITLE
espArtnetNode_2.0.0_b5d_ESP01.bin TX output insted of GPIO2

### ISSUE THREAD

**Issue by legurd** [mtongnz/ESP8266_ArtNetNode_v2#54]
espArtnetNode_2.0.0_b5d_ESP01.bin has TX output instead of GPIO2. Would be nice to have GPIO2 as DMX ouput.

**Comment by mtongnz** [comment]
I've done it to allow 1 port of RDM on the ESP01 - GPIO2 is used for the RDM direction on that chip.  Feel free to change it if you wish - the source is online.  You'll need to either disable the RDM functionality or make another pin direction.   Let me know how you go.

**Comment by mtongnz** [comment]
I have decided not to implement this in the main source.  Closing this request
