### ISSUE TITLE
Esp dont connected with WIFI

### ISSUE THREAD

**Issue by Pascale14** [mtongnz/ESP8266_ArtNetNode_v2#56]
Hey the ESP Node mcu will dont connected with my WIFI Router. Why? Do you have a answer for me ? 

Thanks

**Comment by mtongnz** [comment]
I can't possibly answer that with so little info.

Is your WiFi 2.4GHz?  5GHz wont work with the ESP8266.
Have you tried other sketches?  Do they work?
Does the ESP present you with a hotspot?  Can you connect to it?  Did you enter your WiFi details into the web UI and then do a hard reset of the ESP?

Let me know how you go.

**Comment by mtongnz** [comment]
I'm assuming this issue was resolved as you haven't replied
