### ISSUE TITLE
are necessary MAX485 for WS2812 Led Strip?

### ISSUE THREAD

**Issue by hamedmaleki1366** [mtongnz/ESP8266_ArtNetNode_v2#59]
hi all ,
sorry for my english.

i need only show Jinx Provided Data on LED Strip , Are Necessary to use from MAX485?

can i use from node_pix_only_v2.png Schema, with out PIX_B connections.

what's basic connection needed for this.

thank you.

**Comment by 4bWM1a0SGxov2IM4BHre** [comment]
Hi, no they are not. I'm running 300 odd led's from the 3.3v data pin on a NodeMCU. You are prob better posting to the Instructables forum btw.

https://www.instructables.com/id/Artnet-LED-Pixels-With-ESP8266/
