### ISSUE TITLE
MATRIX NOT WORKING WITH ESP8266_ArtNetNode_v2 AND WEMOS D1 PLEASE HELP ME OUT

### ISSUE THREAD

**Issue by lampenschakelen** [mtongnz/ESP8266_ArtNetNode_v2#83]
Hi Mtongz, 

Thanks al lot for making the program with the esp8266. 
I hope you can help me out. I don't get it to work with my wemos d1. 

I connect led data pin to the TX pin on my wemos d1. 
And i used the follow code:
https://pastecode.xyz/view/028e6939 

I used the ws2812 led stip total of 13 by 13 = 169 leds.

i add some picutres of the setup. 

I tested the setup with the folowing great program: 
https://github.com/toblum/McLighting

When i press now on start output the color is going to white. 
But it's not changing to the colors on JINX! Screen. 

So there is communication from the JINX! software to the wemos d1 with the led strips. But it's not changing to the right matrix.

I hope somebody can help me out. 
To fix it '

Best regards, 
![f5lw3opjcuulpp6 large](https://user-images.githubusercontent.com/26557215/35485727-e65fed66-0463-11e8-8002-48d2678d3b7d.jpg)
![fl11iy0jcuulpot large](https://user-images.githubusercontent.com/26557215/35485728-e67c2d96-0463-11e8-9be4-714f6e68ff4f.jpg)
![fmv4iefjcuulpov large](https://user-images.githubusercontent.com/26557215/35485729-e6971728-0463-11e8-94e6-648362d63e2c.jpg)
![fqyogvkjcuulpou large](https://user-images.githubusercontent.com/26557215/35485730-e6b0ca2e-0463-11e8-9afe-4855ea29998b.jpg)
![fst5zx6jcuulpp5 large](https://user-images.githubusercontent.com/26557215/35485731-e6ca38ec-0463-11e8-8625-61a1b66acff2.jpg)
![fvzvs66jcuulpp4 large](https://user-images.githubusercontent.com/26557215/35485732-e6e327d0-0463-11e8-92d1-5ea5719e53d9.jpg)
![webinterface wemos d1](https://user-images.githubusercontent.com/26557215/35485769-71589080-0464-11e8-8fed-b8c7a332724f.JPG)

Lampen Schakelen

**Comment by ElToberino** [comment]
Pixels only showing white light is a well known problem, which has been solved some months ago by a user commenting the instructable. If you're compiling the source code, you have to set the ESP-CPU frequency to 160 Mhz. Default frequency is 80 Mhz, but this causes the malfunction.
The other, more easier way is just flashing the precompiled .bin-file available in this github.
