### ISSUE TITLE
esp_Artnet_RDM_isolated_v2 partlist

### ISSUE THREAD

**Issue by FaGitt** [mtongnz/ESP8266_ArtNetNode_v2#89]
Hi,

I just started reading electronic schematics, so please be patient to me, if I'm too dump to find the right info.

What kind of caps are used or where can I find a partlist for the isolated one?
I just can find descriptions like C12 in the schematics...

I hope you can help me.

Thank you!

**Comment by mtongnz** [comment]
I've put a BOM in the schematics folder.  The caps are all simply for power filtering so values aren't too important.
