### ISSUE TITLE
Source code and Wemos

### ISSUE THREAD

**Issue by nll41** [mtongnz/ESP8266_ArtNetNode_v2#90]
Hello
I have flashed a Wemos D1 with the wemos .bin file, and i works perfectly.
But I can't make it to work when I compile the source code myself.
Has anyone tried with succes?

best regards
Niels

**Comment by thomsenle** [comment]
i have the same problem :( the compiled sourcecode does not work on the wemos

**Comment by thomsenle** [comment]
Yes, have changed the ports according to my setup. Want to use txd2/gpio4/d2 as output for a single line of pixels. Enabled  "esp01 mode" and changed  pinout to my setup. I played arround a little  last evening and all that happened was that the strips turned on at full white. Have to take a deeper look this evening with osciloscope.

**Comment by bombcheck** [comment]
Hm... The only time I had a full white matrix was when I compiled with 80 MHz instead of 160 MHz.

**Comment by bombcheck** [comment]
TX on Wemos should be GPIO 1 in the code.

**Comment by bombcheck** [comment]
Can you give us the exact pinout you used in your code?

**Comment by thomsenle** [comment]
will do this evening... in the office right now. 

Grüsse aus Leipzig

**Comment by nll41** [comment]
Hello
Thanks for the advice, I changed to 160MHz and recompiled, now it works :-)
best regards Niels

**Comment by thomsenle** [comment]
same here ;)

**Comment by bombcheck** [comment]
Great to hear it is working now.

**Comment by bombcheck** [comment]
So I think this one can be closed then. :)
